import { Feather } from '@expo/vector-icons';
import { useAuth, useUser } from '@clerk/expo';
import { useQueryClient } from '@tanstack/react-query';
import { router } from 'expo-router';
import React, { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { ActionButton, BrandMark, ScreenHeader } from '@/components/MoqawilUI';
import { useColors } from '@/hooks/useColors';
import { getListAdminContractorsQueryKey, type AdminContractor, type AdminContractorInput, useCreateAdminContractor, useDeleteAdminContractor, useListAdminContractors, useUpdateAdminContractor } from '@workspace/api-client-react';

const blank = (): AdminContractorInput => ({ businessName: '', city: '', businessNameArabic: '', wilayat: '', bio: '', bioArabic: '', serviceArea: '', phone: '', evaluationNotes: '', adminRating: null, agreedContractAmountOmaniRial: null, isVerified: false, isPublished: false });
const errorMessage = (error: unknown) => error instanceof Error ? error.message : 'The server could not save this change.';
export default function AdminScreen() {
 const colors=useColors(), insets=useSafeAreaInsets(), client=useQueryClient(); const {isLoaded,isSignedIn}=useAuth(); const {user}=useUser();
 const isAdmin=(user?.publicMetadata as Record<string,unknown> | undefined)?.role==='admin'||(user?.publicMetadata as Record<string,unknown> | undefined)?.isAdmin===true;
 const contractors=useListAdminContractors({query:{queryKey:getListAdminContractorsQueryKey(),enabled:isAdmin}});
 const [form,setForm]=useState<AdminContractorInput>(blank()); const [editing,setEditing]=useState<string|null>(null); const [showForm,setShowForm]=useState(false);
 const invalidate=()=>client.invalidateQueries({queryKey:getListAdminContractorsQueryKey()});
 const create=useCreateAdminContractor({mutation:{onSuccess:()=>{invalidate();setShowForm(false);setForm(blank());},onError:(e)=>Alert.alert('Server validation',errorMessage(e))}});
 const update=useUpdateAdminContractor({mutation:{onSuccess:invalidate,onError:(e)=>Alert.alert('Server validation',errorMessage(e))}});
 const archive=useDeleteAdminContractor({mutation:{onSuccess:invalidate,onError:(e)=>Alert.alert('Archive failed',errorMessage(e))}});
 const set=(key:keyof AdminContractorInput,value:string)=>setForm(v=>({...v,[key]:value}));
 const begin=(c?:AdminContractor)=>{if(c){setEditing(c.id);setForm({businessName:c.businessName,businessNameArabic:c.businessNameArabic??'',city:c.city,wilayat:c.wilayat??'',bio:c.bio??'',bioArabic:c.bioArabic??'',serviceArea:c.serviceArea??'',phone:c.phone??'',evaluationNotes:c.evaluationNotes??'',adminRating:c.adminRating??null,agreedContractAmountOmaniRial:c.agreedContractAmountOmaniRial??null,isVerified:c.isVerified,isPublished:c.isPublished});}else{setEditing(null);setForm(blank());}setShowForm(true);};
 if(!isLoaded)return <View style={[styles.center,{backgroundColor:colors.background}]}><ActivityIndicator color={colors.primary}/></View>;
 if(!isSignedIn||!isAdmin)return <View style={[styles.center,{backgroundColor:colors.background}]}><BrandMark/><Text style={[styles.title,{color:colors.foreground}]}>Admin access required</Text><ActionButton label={isSignedIn?'Go back':'Sign in'} onPress={()=>isSignedIn?router.back():router.push('/sign-in')}/></View>;
 const save=()=>{if(form.businessName.trim().length<2||form.city.trim().length<2){Alert.alert('Missing details','Business name and city are required.');return;}const data={...form,businessName:form.businessName.trim(),city:form.city.trim(),adminRating:form.adminRating===null?null:Number(form.adminRating)||null,agreedContractAmountOmaniRial:form.agreedContractAmountOmaniRial===null?null:Number(form.agreedContractAmountOmaniRial)||null};editing?update.mutate({id:editing,data}):create.mutate({data});};
 return <View style={[styles.page,{backgroundColor:colors.background}]}><ScrollView contentContainerStyle={{paddingTop:insets.top+16,paddingBottom:45}} keyboardShouldPersistTaps="handled"><View style={styles.content}><View style={styles.top}><Pressable testID="admin-back" onPress={()=>router.back()}><Feather name="arrow-left" size={20} color={colors.foreground}/></Pressable><BrandMark compact/></View><ScreenHeader title="إدارة المقاولين" subtitle="Contractor moderation & records" right={<Pressable testID="add-contractor" onPress={()=>begin()}><Feather name="plus-circle" size={26} color={colors.primary}/></Pressable>}/>
 {contractors.isLoading?<ActivityIndicator color={colors.primary}/>:null}{contractors.isError?<Text style={{color:colors.mutedForeground}}>Unable to load server contractors. Please retry.</Text>:null}
 {contractors.data?.map(c=><View key={c.id} style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={styles.row}><View style={{flex:1}}><Text style={[styles.name,{color:colors.foreground}]}>{c.businessName} {c.businessNameArabic?`/ ${c.businessNameArabic}`:''}</Text><Text style={[styles.meta,{color:colors.mutedForeground}]}>{c.city}{c.wilayat?` · ${c.wilayat}`:''} · {c.accountLinkStatus}</Text><Text style={[styles.meta,{color:colors.mutedForeground}]}>{c.isPublished?'Published':'Hidden'} · {c.isVerified?'Verified':'Unverified'}</Text></View><Pressable testID={`edit-contractor-${c.id}`} onPress={()=>begin(c)}><Feather name="edit-2" size={18} color={colors.primary}/></Pressable></View><View style={styles.actions}><Pressable testID={`toggle-verify-${c.id}`} onPress={()=>update.mutate({id:c.id,data:{isVerified:!c.isVerified}})}><Text style={[styles.link,{color:colors.primary}]}>{c.isVerified?'Unverify':'Verify'}</Text></Pressable><Pressable testID={`toggle-publish-${c.id}`} onPress={()=>update.mutate({id:c.id,data:{isPublished:!c.isPublished}})}><Text style={[styles.link,{color:colors.primary}]}>{c.isPublished?'Unpublish':'Publish'}</Text></Pressable><Pressable testID={`archive-contractor-${c.id}`} onPress={()=>Alert.alert('Archive contractor?','This archives the server contractor profile.',[{text:'Cancel',style:'cancel'},{text:'Archive',style:'destructive',onPress:()=>archive.mutate({id:c.id,params:{confirm:true}})}])}><Text style={[styles.link,{color:'#C55353'}]}>Archive</Text></Pressable></View></View>)}
 {showForm?<View style={[styles.form,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.name,{color:colors.foreground}]}>{editing?'Edit server contractor':'Add server contractor'}</Text>{([['businessName','Business name / اسم المنشأة'],['businessNameArabic','Arabic business name / الاسم بالعربية'],['city','City / المدينة'],['wilayat','Wilayat / الولاية'],['serviceArea','Service area / منطقة الخدمة'],['phone','Phone / الهاتف'],['bio','Bio / نبذة'],['bioArabic','Arabic bio / النبذة بالعربية'],['evaluationNotes','Admin evaluation notes / ملاحظات الإدارة'],['adminRating','Admin rating (1–5) / تقييم الإدارة'],['agreedContractAmountOmaniRial','Agreed amount OMR / قيمة العقد'] ] as const).map(([key,label])=><View key={key}><Text style={[styles.label,{color:colors.foreground}]}>{label}</Text><TextInput testID={`contractor-field-${key}`} value={String(form[key]??'')} onChangeText={v=>set(key,v)} multiline={key==='bio'||key==='bioArabic'||key==='evaluationNotes'} keyboardType={key==='adminRating'||key==='agreedContractAmountOmaniRial'?'decimal-pad':'default'} textAlign={key.includes('Arabic')?'right':'left'} style={[styles.input,{color:colors.foreground,borderColor:colors.border,backgroundColor:colors.background}]}/></View>)}<View style={styles.actions}><Pressable testID="form-verified" onPress={()=>setForm(v=>({...v,isVerified:!v.isVerified}))}><Text style={[styles.link,{color:colors.primary}]}>{form.isVerified?'✓ Verified':'Verify'}</Text></Pressable><Pressable testID="form-published" onPress={()=>setForm(v=>({...v,isPublished:!v.isPublished}))}><Text style={[styles.link,{color:colors.primary}]}>{form.isPublished?'✓ Published':'Publish intent'}</Text></Pressable></View><View testID="save-server-contractor"><ActionButton label={create.isPending||update.isPending?'Saving…':'Save server contractor'} onPress={save}/></View><Pressable testID="cancel-contractor-form" onPress={()=>setShowForm(false)}><Text style={[styles.link,{color:colors.mutedForeground}]}>Cancel</Text></Pressable></View>:null}</View></ScrollView></View>;
}
const styles=StyleSheet.create({page:{flex:1},center:{flex:1,alignItems:'center',justifyContent:'center',gap:18,padding:25},content:{paddingHorizontal:20,gap:13},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{fontSize:22,fontWeight:'800'},card:{borderWidth:1,borderRadius:17,padding:14,gap:11},row:{flexDirection:'row',gap:10},name:{fontSize:15,fontWeight:'800'},meta:{fontSize:11,marginTop:3},actions:{flexDirection:'row',flexWrap:'wrap',gap:16},link:{fontSize:12,fontWeight:'800'},form:{borderWidth:1,borderRadius:18,padding:15,gap:10,marginTop:8},label:{fontSize:11,fontWeight:'800',marginBottom:5},input:{borderWidth:1,borderRadius:11,minHeight:43,paddingHorizontal:10,fontSize:13}});